Repository ConfigMate/configmate, pull requests merged in 2023-09, with the labels that each got.

#2 patch/added bump version
  .bumpversion.cfg
  .github/workflows/bump_version.yml
  .gitignore
  Makefile
  go.mod
Labels: devops

#3 devops/fixing bump version
  .bumpversion.cfg
  .github/events/bump_version_patch.json
  .github/workflows/bump_version.yml
  Makefile
Labels: devops

#4 patch/Simple change to test bump version
  anaylzer/analyzer.go
Labels: devops

#5 patch/fixing bump version action
  .bumpversion.cfg
  .github/workflows/bump_version.yml
  .gitignore
  Makefile
Labels: devops

#8 patch/removed-tag-from-bumpv-options
  .github/workflows/bump_version.yml
Labels: devops

#9 patch/adding simple useless change
  anaylzer/analyzer.go
Labels: devops

#10 patch/testing bump version
  .github/workflows/bump_version.yml
Labels: devops

#13 devops/added linting, test, test coverage, and build checks
  .github/workflows/lint_test_build.yml
  .gitignore
Labels: devops

#12 docs/added PR convention validation and versioning instructions
  .github/workflows/pr_validation.yml
  .secrets
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
Labels: documentation, devops

#14 devops/removed secrets file
  .secrets
Labels: devops

#19 docs/fixing the PR template
  .github/pull_request_template.md
Labels: documentation
